# Installing Scikit Learn

In [4]:
!pip3 install -U scikit-learn scipy matplotlib

Requirement already up-to-date: scipy in c:\users\nilsvn\appdata\local\programs\python\python36-32\lib\site-packages (1.4.1)
Requirement already up-to-date: matplotlib in c:\users\nilsvn\appdata\local\programs\python\python36-32\lib\site-packages (3.2.1)
Could not build wheels for scipy, since package 'wheel' is not installed.
Could not build wheels for matplotlib, since package 'wheel' is not installed.
Could not build wheels for numpy, since package 'wheel' is not installed.
Could not build wheels for cycler, since package 'wheel' is not installed.
Could not build wheels for kiwisolver, since package 'wheel' is not installed.
Could not build wheels for python-dateutil, since package 'wheel' is not installed.
Could not build wheels for pyparsing, since package 'wheel' is not installed.
Could not build wheels for six, since package 'wheel' is not installed.


You should consider upgrading via the 'c:\users\nilsvn\appdata\local\programs\python\python36-32\python.exe -m pip install --upgrade pip' command.


In [191]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics
import time
from sklearn.preprocessing import StandardScaler

#remove
from sklearn.impute import SimpleImputer


In [150]:
df_attack = pd.read_csv ("C:/Users/NilsvN/Desktop/Research/Azure/Attacks/01_brute_force/brute_force_1.csv")

In [151]:
df_attack.shape
df_attack.head

<bound method NDFrame.head of                                 TenantId SourceSystem  \
0   88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
1   88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
2   88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
3   88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
4   88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
5   88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
6   88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
7   88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
8   88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
9   88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
10  88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
11  88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
12  88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
13  88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
14  88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
15  88ddc2a5-36fd-403a-ac48-8cf61c0aee88     Azure AD   
1

In [61]:
df_attack['Class'] = 1 #create new 'Class' column containing only 1's.

In [62]:
df_attack.shape
df_attack.head

<bound method NDFrame.head of                       Date (UTC)                            Request ID  \
0    2020-06-03T17:17:34.158334Z  2a853978-397d-4b00-b26c-a948c8b22900   
1   2020-06-03T17:14:26.6779753Z  b5f788f8-9214-4dc1-9921-fc356f807900   
2   2020-06-03T17:14:06.6567347Z  481fab2f-4308-4873-8f80-918483f16c00   
3   2020-06-03T17:14:00.6350145Z  db16e64f-e49f-4155-8c95-57a71b397600   
4   2020-06-03T17:13:55.2197917Z  ea692ab8-5d8c-4b2a-a1d6-ac119504d600   
5   2020-06-03T17:13:50.8388367Z  5df3b695-c913-4bd5-8410-682092716700   
6   2020-06-03T17:13:46.8759191Z  ea692ab8-5d8c-4b2a-a1d6-ac111903d600   
7   2020-06-03T17:13:36.3920884Z  5df3b695-c913-4bd5-8410-6820d26f6700   
8   2020-06-03T17:13:31.5623387Z  a0f5fb87-a0b7-432c-b532-64d588087400   
9    2020-06-03T17:13:26.995345Z  885786b0-4154-403e-8092-eef4ca036900   
10  2020-06-03T17:13:19.6219654Z  45b0d0d1-63f1-4958-98ac-88cb04cf7200   
11  2020-06-03T17:13:10.0746202Z  db16e64f-e49f-4155-8c95-57a778307600   

       

In [94]:
def get_df(attack_path, normal_path):
    df_attack = pd.read_csv(attack_path)
    df_normal = pd.read_csv(normal_path)
    
    df_attack['Class'] = 1 #create new 'Class' column containing only 1's.
    df_normal['Class'] = 0 #create new 'Class' column containing only 0's.
    
    df_res = pd.concat([df_attack, df_normal], ignore_index=True)
    return df_res

In [208]:
def get_X_y(df):
    X = df.drop('Class', axis=1)
    y = df['Class']
    return X, y

Eventually when testing multiclass data (4 labels, normal + 3 attack types) will I be able to change the threshold?

In [42]:
iris= datasets.load_iris()

In [43]:
X = iris.data[:,2]

In [179]:
y = iris.target

In [180]:
def preprocess(df):
    imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
    imputer = imputer.fit(df[['Join Type', 'MFA result']])
    temp = imputer.transform(df[['Join Type', 'MFA result']])
    print(temp.shape)
    print(temp.size)
    print(df['Join Type'].shape)
    print(df['Join Type'])
    df['Join Type'].values.reshape(-1,1)
    print(df['Join Type'].shape)
    df['Join Type'] = temp
    return df

#     imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
#     imputer = imputer.fit(df)
#     df[:] = imputer.transform(df)
#     return df
    
    
    

In [146]:
def SVM(X, y, threshold=0.5): #todo: use threshold param
    X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=4)
    X_train_mod = X_train.reshape(-1,1)
    X_test_mod = X_test.reshape(-1,1)
    y_train_mod = y_train.reshape(-1,1)
    y_test_mod = y_test.reshape(-1,1)
    model= svm.SVC(kernel='linear')
    model.fit(X_train_mod, y_train_mod)
    y_pred = model.predict(X_test_mod)
    
    print(metrics.confusion_matrix(y_test_mod, y_pred))
    print(metrics.classification_report(y_test_mod, y_pred, digits=3))
    
    ACC = metrics.accuracy_score(y_test_mod, y_pred)
    PRC = metrics.precision_score(y_test_mod, y_pred, average=None)
    REC = metrics.recall_score(y_test_mod, y_pred, average=None)
    return ACC, PRC, REC
    

In [197]:
def datetime_string_to_epoch(str):
    t = time.strptime(str, '%Y-%m-%dT%H:%M:%S.%fZ')
    return time.mktime(t)

In [198]:
example = '2020-06-11T23:53:35.978Z'
print(datetime_string_to_epoch(example))



1591912415.0


In [210]:
attack_path = "C:/Users/NilsvN/Desktop/Research/Azure/Attacks/01_brute_force/brute_force_1.csv"
normal_path = "C:/Users/NilsvN/Desktop/Research/Azure/30_day_login/30days_anonymized_sigin_logs_column_corrected.csv"

df = get_df(attack_path, attack_path)
df = df[['TimeGenerated', 'CorrelationId', 'ConditionalAccessStatus', 'Class']]
df['TimeGenerated'] = df['TimeGenerated'].map(datetime_string_to_epoch)
X, y = get_X_y(df)
print(X)
print(y)

    TimeGenerated                         CorrelationId  \
0    1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
1    1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
2    1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
3    1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
4    1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
5    1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
6    1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
7    1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
8    1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
9    1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
10   1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
11   1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
12   1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
13   1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
14   1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa   
15   1.591912e+09  046cb21b-7071-4625-bd08-1b192ca996aa 

In [52]:
ACC, PRC, REC = SVM()
print('ACC: ' + str(ACC))
print('PRC: ' + str(PRC))
print('REC: ' + str(REC))


[[16  0  0]
 [ 0  4  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0      1.000     1.000     1.000        16
           1      1.000     0.800     0.889         5
           2      0.900     1.000     0.947         9

    accuracy                          0.967        30
   macro avg      0.967     0.933     0.945        30
weighted avg      0.970     0.967     0.966        30

ACC: 0.9666666666666667
PRC: [1.  1.  0.9]
REC: [1.  0.8 1. ]


c:\users\nilsvn\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
